In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

results = pd.read_csv('/content/results.csv')
print("Dataset Shape:", results.shape)

results.head()

Dataset Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [3]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49417 non-null  float64
 4   away_score  49417 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [4]:
results.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [5]:
pd.read_csv('/content/results.csv')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [8]:
import os

print(os.listdir('/content'))

['.config', 'former_names.csv', 'shootouts.csv', 'drive', 'results.csv', 'goalscorers.csv', '.ipynb_checkpoints', 'sample_data']

In [9]:
import pandas as pd
results = pd.read_csv('/content/results.csv')
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [10]:
import pandas as pd

results = pd.read_csv('/content/results.csv')
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [11]:
pd.read_csv('/content/drive/MyDrive/...')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/...'

In [12]:
import os

print(os.listdir('/content'))

['.config', 'former_names.csv', 'shootouts.csv', 'drive', 'results.csv', 'goalscorers.csv', '.ipynb_checkpoints', 'sample_data']

In [13]:
import pandas as pd

results = pd.read_csv('/content/results.csv')

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [14]:
results = pd.read_csv('/content/drive/MyDrive/NLP_Project/results.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/NLP_Project/results.csv'

In [15]:
import os

print(os.listdir('/content'))

['.config', 'former_names.csv', 'shootouts.csv', 'drive', 'results.csv', 'goalscorers.csv', '.ipynb_checkpoints', 'sample_data']

In [16]:
import pandas as pd

results = pd.read_csv('results.csv')

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [17]:
print(results.shape)

(49477, 9)

In [18]:
!pwd
!ls

/content
drive		  goalscorers.csv  sample_data
former_names.csv  results.csv	   shootouts.csv

In [19]:
print(os.listdir('/content'))

['.config', 'former_names.csv', 'shootouts.csv', 'drive', 'results.csv', 'goalscorers.csv', '.ipynb_checkpoints', 'sample_data']

In [20]:
pd.read_csv('/content/results.csv')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [38]:
import pandas as pd
drive_results_example = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print("Example Drive Results Shape:", drive_results_example.shape)
display(drive_results_example.head())

Example Drive Results Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

### Loading the other CSV files from `/content`

Based on the output of `os.listdir('/content')`, the following CSV files are available in your Colab environment:
- `former_names.csv`
- `shootouts.csv`
- `results.csv` (already loaded)
- `goalscorers.csv`

In [28]:
former_names = pd.read_csv('/content/former_names.csv')
print("Former Names Shape:", former_names.shape)
display(former_names.head())

Former Names Shape: (36, 4)

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [29]:
shootouts = pd.read_csv('/content/shootouts.csv')
print("Shootouts Shape:", shootouts.shape)
display(shootouts.head())

Shootouts Shape: (678, 5)

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

In [30]:
goalscorers = pd.read_csv('/content/goalscorers.csv')
print("Goalscorers Shape:", goalscorers.shape)
display(goalscorers.head())

Goalscorers Shape: (47639, 8)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

If you specifically need to load files from your Google Drive, please make sure the file paths are exact, including any subfolders. For example, if `results.csv` were in a folder called `my_project` inside `MyDrive`, the path would be `/content/drive/MyDrive/my_project/results.csv`.

In [33]:
# This cell previously tried to load a file from Google Drive using a placeholder.
# Based on your environment, the CSV files (results.csv, former_names.csv, shootouts.csv, goalscorers.csv)
# are actually located in the `/content` directory.
# If you still wish to load a *different* file from Google Drive, replace 'your_actual_file_name.csv'
# with its exact name and full path, e.g., '/content/drive/MyDrive/my_folder/my_file.csv'.

# Example of how you would load a file that is in /content:
# results_from_content = pd.read_csv('/content/results.csv')
# results_from_content.head()

### How to access files from your Google Drive folder

1.  **Check your Google Drive contents:** To see what's in your 'My Drive' and identify the folder containing your files, run the following command:

In [34]:
!ls /content/drive/MyDrive

'5aa522e4-9dd9-469d-a6ae-6f4ec3999bbd - 22UG1-0824 MADUSHAN K.M.L..jpeg'
'Bulk create for domain tishanarunalu.short.gy.gsheet'
 CIT-24-01-0563.drawio
'Colab Notebooks'
'Contact Information.gform'
'Customer Feedback (1).gform'
'Customer Feedback.gform'
'Customer Feedback (Responses).gsheet'
'Event Registration (File responses)'
'Event Registration.gform'
'Google Form'
'IMG_20250320_210044 - Thusindee Thisasya.jpg'
 NLP_Tishan
'Porfolio Contact form.gsheet'
'Saved from Chrome'
 Tishan_Resume.pdf
'Untitled spreadsheet.gsheet'

2.  **Identify the correct path:** From the output of the previous command, find the folder name that contains your `former_names.csv`, `shootouts.csv`, `results.csv`, and `goalscorers.csv` files. Let's assume for this example that the folder is named `MySharedFiles` (you will need to replace this with the actual folder name).

3.  **Load the files using the full path:** Now, you can load your files using the full path like this:

In [36]:
# Replace 'MySharedFiles' with the actual name of your folder in Google Drive, which appears to be 'NLP_Tishan'
# You can adapt these lines for the other CSV files as well

drive_former_names = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/former_names.csv')
print("Drive Former Names Shape:", drive_former_names.shape)
display(drive_former_names.head())

drive_shootouts = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/shootouts.csv')
print("Drive Shootouts Shape:", drive_shootouts.shape)
display(drive_shootouts.head())

drive_goalscorers = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/goalscorers.csv')
print("Drive Goalscorers Shape:", drive_goalscorers.shape)
display(drive_goalscorers.head())

drive_results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print("Drive Results Shape:", drive_results.shape)
display(drive_results.head())

Drive Former Names Shape: (36, 4)

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

Drive Shootouts Shape: (678, 5)

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

Drive Goalscorers Shape: (47639, 8)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

Drive Results Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [39]:
print(results.shape)
print(results.columns)
results.head()

(49477, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [40]:
results.isnull().sum()

date           0
home_team      0
away_team      0
home_score    60
away_score    60
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [41]:
print("Duplicates:", results.duplicated().sum())

Duplicates: 0

In [43]:
results = results.drop_duplicates()

In [44]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49417 non-null  float64
 4   away_score  49417 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [45]:
questions = [
    "Who won the match between Brazil and Argentina?",
    "What was the score of Germany vs France?",
    "Which team won the FIFA World Cup Final?"
]

for q in questions:
    print(q)

Who won the match between Brazil and Argentina?
What was the score of Germany vs France?
Which team won the FIFA World Cup Final?

In [46]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [48]:
import nltk
import re

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added to resolve the LookupError

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "Who won the FIFA World Cup Final 2014?"

text = text.lower()

text = re.sub(r'[^a-zA-Z0-9 ]','',text)

tokens = word_tokenize(text)

filtered = [word for word in tokens if word not in stopwords.words('english')]

print(filtered)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

['fifa', 'world', 'cup', 'final', '2014']

In [51]:
results.to_csv('cleaned_results.csv', index=False)

In [52]:
print(results.shape)
print(results.columns)

(49477, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')