<a href="https://colab.research.google.com/github/eshan14git/football-qa-nlp/blob/tishan-dev/Tishan_SVM_GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print("Dataset Shape:", results.shape)

results.head()

Dataset Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49417 non-null  float64
 4   away_score  49417 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [ ]:
results.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

In [ ]:
pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [ ]:
import os

print(os.listdir('/content'))

In [ ]:
import pandas as pd
results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
import pandas as pd

results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'sample_data', 'drive']

In [ ]:
import pandas as pd

results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'sample_data', 'drive']

In [ ]:
import pandas as pd

results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
print(results.shape)

(49477, 9)

In [ ]:
!pwd
!ls

/content
drive  sample_data

In [ ]:
print(os.listdir('/content'))

['.config', 'sample_data', 'drive']

In [ ]:
pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [ ]:
import pandas as pd
drive_results_example = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print("Example Drive Results Shape:", drive_results_example.shape)
display(drive_results_example.head())

Example Drive Results Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

### Loading the other CSV files from `/content`

Based on the output of `os.listdir('/content')`, the following CSV files are available in your Colab environment:
- `former_names.csv`
- `shootouts.csv`
- `results.csv` (already loaded)
- `goalscorers.csv`

In [ ]:
former_names = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/former_names.csv')
print("Former Names Shape:", former_names.shape)
display(former_names.head())

Former Names Shape: (36, 4)

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [ ]:
shootouts = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/shootouts.csv')
print("Shootouts Shape:", shootouts.shape)
display(shootouts.head())

Shootouts Shape: (678, 5)

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

In [ ]:
goalscorers = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/goalscorers.csv')
print("Goalscorers Shape:", goalscorers.shape)
display(goalscorers.head())

Goalscorers Shape: (47639, 8)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

If you specifically need to load files from your Google Drive, please make sure the file paths are exact, including any subfolders. For example, if `results.csv` were in a folder called `my_project` inside `MyDrive`, the path would be `/content/drive/MyDrive/my_project/results.csv`.

In [ ]:
# This cell previously tried to load a file from Google Drive using a placeholder.
# Based on your environment, the CSV files (results.csv, former_names.csv, shootouts.csv, goalscorers.csv)
# are actually located in the `/content` directory.
# If you still wish to load a *different* file from Google Drive, replace 'your_actual_file_name.csv'
# with its exact name and full path, e.g., '/content/drive/MyDrive/my_folder/my_file.csv'.

# Example of how you would load a file that is in /content:
# results_from_content = pd.read_csv('/content/results.csv')
# results_from_content.head()

### How to access files from your Google Drive folder

1.  **Check your Google Drive contents:** To see what's in your 'My Drive' and identify the folder containing your files, run the following command:

In [ ]:
!ls /content/drive/MyDrive

'5aa522e4-9dd9-469d-a6ae-6f4ec3999bbd - 22UG1-0824 MADUSHAN K.M.L..jpeg'
'Bulk create for domain tishanarunalu.short.gy.gsheet'
 CIT-24-01-0563.drawio
'Colab Notebooks'
'Contact Information.gform'
'Customer Feedback (1).gform'
'Customer Feedback.gform'
'Customer Feedback (Responses).gsheet'
'Event Registration (File responses)'
'Event Registration.gform'
'Google Form'
'IMG_20250320_210044 - Thusindee Thisasya.jpg'
 NLP_Tishan
'Porfolio Contact form.gsheet'
'Saved from Chrome'
 Tishan_Resume.pdf
'Untitled spreadsheet.gsheet'

2.  **Identify the correct path:** From the output of the previous command, find the folder name that contains your `former_names.csv`, `shootouts.csv`, `results.csv`, and `goalscorers.csv` files. Let's assume for this example that the folder is named `MySharedFiles` (you will need to replace this with the actual folder name).

3.  **Load the files using the full path:** Now, you can load your files using the full path like this:

In [ ]:
# Replace 'MySharedFiles' with the actual name of your folder in Google Drive, which appears to be 'NLP_Tishan'
# You can adapt these lines for the other CSV files as well

drive_former_names = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/former_names.csv')
print("Drive Former Names Shape:", drive_former_names.shape)
display(drive_former_names.head())

drive_shootouts = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/shootouts.csv')
print("Drive Shootouts Shape:", drive_shootouts.shape)
display(drive_shootouts.head())

drive_goalscorers = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/goalscorers.csv')
print("Drive Goalscorers Shape:", drive_goalscorers.shape)
display(drive_goalscorers.head())

drive_results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print("Drive Results Shape:", drive_results.shape)
display(drive_results.head())

Drive Former Names Shape: (36, 4)

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

Drive Shootouts Shape: (678, 5)

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

Drive Goalscorers Shape: (47639, 8)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

Drive Results Shape: (49477, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
print(results.shape)
print(results.columns)
results.head()

(49477, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
results.isnull().sum()

date           0
home_team      0
away_team      0
home_score    60
away_score    60
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [ ]:
print("Duplicates:", results.duplicated().sum())

Duplicates: 0

In [ ]:
results = results.drop_duplicates()

In [ ]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  object
 1   home_team   49477 non-null  object
 2   away_team   49477 non-null  object
 3   home_score  49417 non-null  float64
 4   away_score  49417 non-null  float64
 5   tournament  49477 non-null  object
 6   city        49477 non-null  object
 7   country     49477 non-null  object
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [ ]:
questions = [
    "Who won the match between Brazil and Argentina?",
    "What was the score of Germany vs France?",
    "Which team won the FIFA World Cup Final?"
]

for q in questions:
    print(q)

Who won the match between Brazil and Argentina?
What was the score of Germany vs France?
Which team won the FIFA World Cup Final?

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import nltk
import re

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab') # Added to resolve the LookupError

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "Who won the FIFA World Cup Final 2014?"

text = text.lower()

text = re.sub(r'[^a-zA-Z0-9 ]','',text)

tokens = word_tokenize(text)

filtered = [word for word in tokens if word not in stopwords.words('english')]

print(filtered)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

['fifa', 'world', 'cup', 'final', '2014']

In [ ]:
results.to_csv('cleaned_results.csv', index=False)

In [ ]:
print(results.shape)
print(results.columns)

(49477, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

# Task
The task is to build a Natural Language Question Answering (NLQA) system that can answer questions about football match results using a provided dataset ('results.csv'). The system should preprocess natural language queries, identify key entities and question types, extract relevant information from the dataset, and provide textual answers for different types of questions such as 'Who won', 'What was the score', and 'Which team won a tournament'. Finally, the system will be tested with sample questions and its capabilities summarized.

## Define Text Preprocessing Function

### Subtask:
Create a function to preprocess natural language queries by lower-casing, removing punctuation, tokenizing, and removing stopwords.

**Reasoning**:
I will start by defining the `preprocess_query` function as outlined in the instructions, incorporating lower-casing, punctuation removal, tokenization, and stopword removal.

In [ ]:
import nltk
import re

def preprocess_query(query):
    # Convert to lowercase
    query = query.lower()
    # Remove punctuation and special characters
    query = re.sub(r'[^a-z0-9\s]', '', query)
    # Tokenize the query
    tokens = nltk.word_tokenize(query)
    # Remove stopwords
    stop_words = set(nltk.corpus.stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

print("Preprocess query function defined.")

Preprocess query function defined.

## Identify Team Names in Query

### Subtask:
Create a function to identify potential team names within the preprocessed user query. This will involve comparing tokens from the query against a list of unique team names present in the `results` DataFrame.

**Reasoning**:
Extracting unique team names from the 'home_team' and 'away_team' columns and storing them in a set for efficient lookup.

In [ ]:
all_teams = set(results['home_team']).union(set(results['away_team']))
print(f"Number of unique teams: {len(all_teams)}")

Number of unique teams: 336

**Reasoning**:
Reload the 'results' DataFrame from the CSV file as it was not defined in the previous execution.

In [ ]:
results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
print(results.shape)
print(results.columns)
results.head()

(49477, 9)
Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='object')

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

**Reasoning**:
Reloading the `results` DataFrame and then extracting unique team names from it, as per the plan.

In [ ]:
import pandas as pd

results = pd.read_csv('/content/drive/MyDrive/NLP_Tishan/results.csv')
all_teams = set(results['home_team']).union(set(results['away_team']))
print(f"Number of unique teams: {len(all_teams)}")

Number of unique teams: 336

In [ ]:
import pandas as pd
import os

file_path = '/content/drive/MyDrive/NLP_Tishan/results.csv'

if os.path.exists(file_path):
    print(f"File found at: {file_path}. Attempting to load...")
    results = pd.read_csv(file_path)
    all_teams = set(results['home_team']).union(set(results['away_team']))
    print(f"Number of unique teams: {len(all_teams)}")
else:
    print(f"Error: File not found at {file_path}. Please ensure the file is correctly placed in your Google Drive and the path is correct.")

File found at: /content/drive/MyDrive/NLP_Tishan/results.csv. Attempting to load...
Number of unique teams: 336

## Remount Google Drive

### Subtask:
Forcibly remount Google Drive to ensure proper access to the `/content/drive/MyDrive/NLP_Tishan/results.csv` file.

**Reasoning**:
To forcibly remount Google Drive, I will use the `drive.mount()` function with the `force_remount=True` parameter.

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
print("Google Drive forcibly remounted.")

Mounted at /content/drive
Google Drive forcibly remounted.

**Reasoning**:
Defining the `identify_team_names` function to process a query, tokenize it, and match tokens against the `all_teams` set to identify team names.

In [ ]:
def identify_team_names(query):
    preprocessed_tokens = preprocess_query(query)
    identified_teams = []
    # Iterate through tokens and check if they match any team name
    # This is a simplified approach, a more robust solution might involve
    # checking for multi-word team names or fuzzy matching.
    for team in all_teams:
        team_tokens = team.lower().split()
        # Check if all tokens of a team name are present in the preprocessed query tokens
        if all(token in preprocessed_tokens for token in team_tokens):
            # This simple check might lead to false positives or miss team names if the query is very short
            # For example, if 'united' is a token, it might match 'Manchester United' or 'Newcastle United'
            # A more advanced approach would be to look for sequences of tokens.
            # For now, let's just add the exact team name if all its words are found.
            identified_teams.append(team)

    # Refined approach to handle multi-word team names more accurately
    # It's better to build candidate phrases from the query and check against all_teams
    identified_teams_refined = set()
    query_lower = query.lower()

    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

print("identify_team_names function defined.")

identify_team_names function defined.

**Reasoning**:
Defining the `identify_team_names` function, which preprocesses the input query and then iterates through the `all_teams` set to find team names present in the lowercased query. This approach handles multi-word team names more accurately by checking for exact substrings.

In [ ]:
def identify_team_names(query):
    # Preprocess the query to get individual tokens (not used directly in refined approach but good for consistency)
    preprocessed_tokens = preprocess_query(query) # Keep this call for completeness, though not strictly used in the refined matching

    identified_teams_refined = set()
    query_lower = query.lower()

    # Iterate through all known team names and check if they are substrings of the lowercased query
    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

print("identify_team_names function defined.")

identify_team_names function defined.

**Reasoning**:
Defining the `identify_team_names` function which preprocesses the input query and then iterates through the `all_teams` set to find team names present in the lowercased query. This approach handles multi-word team names more accurately by checking for exact substrings.

In [ ]:
def identify_team_names(query):
    # Preprocess the query to get individual tokens (not used directly in refined approach but good for consistency)
    preprocessed_tokens = preprocess_query(query) # Keep this call for completeness, though not strictly used in the refined matching

    identified_teams_refined = set()
    query_lower = query.lower()

    # Iterate through all known team names and check if they are substrings of the lowercased query
    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

print("identify_team_names function defined.")

identify_team_names function defined.

**Reasoning**:
Implementing the `identify_team_names` function according to the subtask instructions.

In [ ]:
def identify_team_names(query):
    # Preprocess the query (though the tokenized list is not directly used for the refined substring matching,
    # it's good to keep for consistency or future enhancements where individual tokens might be needed).
    preprocessed_tokens = preprocess_query(query)

    identified_teams_refined = set()
    query_lower = query.lower()

    # Iterate through all known team names and check if they are substrings of the lowercased query
    for team_name in all_teams:
        # Using 'in' for substring matching handles multi-word team names more robustly
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

print("identify_team_names function defined.")

identify_team_names function defined.

# Task
The task is to build a Natural Language Question Answering (NLQA) system that can answer questions about football match results using a provided dataset ('results.csv'). The system should preprocess natural language queries, identify key entities and question types, extract relevant information from the dataset, and provide textual answers for different types of questions such as 'Who won', 'What was the score', and 'Which team won a tournament'. Finally, the system will be tested with sample questions and its capabilities summarized.

## Test Identify Team Names Function

### Subtask:
Test the `identify_team_names` function with various sample queries to ensure it accurately extracts team names, including single-word and multi-word team names.

**Reasoning**:
Calling the `identify_team_names` function with a sample query that includes single-word team names as per the first instruction.

In [ ]:
query1 = "Who played between Brazil and Argentina?"
identified_teams1 = identify_team_names(query1)
print(f"Query: '{query1}'\nIdentified Teams: {identified_teams1}\n")

NameError: name 'preprocess_query' is not defined

**Reasoning**:
I need to ensure the `preprocess_query` function is defined before `identify_team_names` is called. I will include the definition of `preprocess_query` and then call `identify_team_names` with the sample query.

In [ ]:
import nltk
import re

def preprocess_query(query):
    # Convert to lowercase
    query = query.lower()
    # Remove punctuation and special characters
    query = re.sub(r'[^a-z0-9\s]', '', query)
    # Tokenize the query
    tokens = nltk.word_tokenize(query)
    # Remove stopwords
    stop_words = set(nltk.corpus.stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

def identify_team_names(query):
    preprocessed_tokens = preprocess_query(query)

    identified_teams_refined = set()
    query_lower = query.lower()

    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

query1 = "Who played between Brazil and Argentina?"
identified_teams1 = identify_team_names(query1)
print(f"Query: '{query1}'\nIdentified Teams: {identified_teams1}\n")

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

**Reasoning**:
To resolve the `LookupError`, I will add `nltk.download('punkt_tab')` before calling `nltk.word_tokenize` in the `preprocess_query` function. This will ensure all necessary NLTK resources are downloaded.

In [ ]:
import nltk
import re

nltk.download('punkt_tab') # Download punkt_tab resource
nltk.download('punkt')
nltk.download('stopwords')

def preprocess_query(query):
    # Convert to lowercase
    query = query.lower()
    # Remove punctuation and special characters
    query = re.sub(r'[^a-z0-9\s]', '', query)
    # Tokenize the query
    tokens = nltk.word_tokenize(query)
    # Remove stopwords
    stop_words = set(nltk.corpus.stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

def identify_team_names(query):
    preprocessed_tokens = preprocess_query(query)

    identified_teams_refined = set()
    query_lower = query.lower()

    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)

    return list(identified_teams_refined)

query1 = "Who played between Brazil and Argentina?"
identified_teams1 = identify_team_names(query1)
print(f"Query: '{query1}'\nIdentified Teams: {identified_teams1}\n")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Query: 'Who played between Brazil and Argentina?'
Identified Teams: ['Argentina', 'Brazil']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

**Reasoning**:
Calling the `identify_team_names` function with a sample query that includes a multi-word team name as per the subtask instructions.

In [ ]:
query2 = "What was the score of a match involving Manchester United?"
identified_teams2 = identify_team_names(query2)
print(f"Query: '{query2}'\nIdentified Teams: {identified_teams2}\n")

Query: 'What was the score of a match involving Manchester United?'
Identified Teams: []

**Reasoning**:
First, I need to check if 'Manchester United' is present in the `all_teams` set to ensure the lookup logic has the correct data.

In [ ]:
print(f"'Manchester United' in all_teams: {'Manchester United' in all_teams}")

query2 = "What was the score of a match involving Manchester United?"
identified_teams2 = identify_team_names(query2)
print(f"Query: '{query2}'\nIdentified Teams: {identified_teams2}\n")

'Manchester United' in all_teams: False
Query: 'What was the score of a match involving Manchester United?'
Identified Teams: []

**Reasoning**:
To find a suitable multi-word team name for testing, I will iterate through the `all_teams` set and print a few examples of team names that contain more than one word.

In [ ]:
multi_word_teams = [team for team in all_teams if ' ' in team]
print("Example multi-word team names from all_teams:")
for i, team in enumerate(multi_word_teams[:10]): # Print first 10 for inspection
    print(f"- {team}")

Example multi-word team names from all_teams:
- Ynys Môn
- Marshall Islands
- Székely Land
- New Zealand
- United States Virgin Islands
- Papua New Guinea
- Antigua and Barbuda
- El Salvador
- Burkina Faso
- Solomon Islands

**Reasoning**:
Using one of the multi-word team names identified in the previous step, I will construct a query and pass it to the `identify_team_names` function to verify its functionality for such cases.

In [ ]:
query3 = "Did New Zealand play against Australia?"
identified_teams3 = identify_team_names(query3)
print(f"Query: '{query3}'\nIdentified Teams: {identified_teams3}\n")

Query: 'Did New Zealand play against Australia?'
Identified Teams: ['New Zealand', 'Australia']

## Define Identify Dates Function

### Subtask:
Create a function to identify potential dates or date ranges within the preprocessed user query. This might involve using regular expressions or date parsing libraries.

**Reasoning**:
Importing necessary libraries and installing `dateutil.parser` if not already installed, as per the first instruction of the subtask. This ensures that the required tools for date identification are available.

In [ ]:
import re
import datetime

try:
    from dateutil.parser import parse
except ImportError:
    print("Installing python-dateutil...")
    !pip install python-dateutil
    from dateutil.parser import parse

print("Date parsing libraries imported and checked.")

Date parsing libraries imported and checked.

**Reasoning**:
Now that the necessary date parsing libraries are imported, I will define the `identify_dates` function. This function will use regular expressions to find common date patterns and then leverage `dateutil.parser.parse` to convert identified date strings into datetime objects, returning a list of successfully parsed dates.

In [ ]:
def identify_dates(query):
    identified_dates = []
    query_lower = query.lower()

    # Preprocess the query to remove punctuation that might interfere with date parsing
    # but keep spaces, digits, hyphens, and COMMAS
    clean_query = re.sub(r'[^a-z0-9\s,-]', '', query_lower) # Keep hyphens and commas for date formats

    # Regex patterns for common date formats
    # YYYY-MM-DD, YYYY/MM/DD, MM-DD-YYYY, MM/DD/YYYY, Month DD YYYY, DD Month YYYY
    date_patterns = [
        r'\b\d{4}[-/]\d{2}[-/]\d{2}\b', # YYYY-MM-DD or YYYY/MM/DD
        r'\b\d{2}[-/]\d{2}[-/]\d{4}\b', # MM-DD-YYYY or MM/DD/YYYY
        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{1,2},\s+\d{4}\b', # Month DD, YYYY
        r'\b\d{1,2}\s+(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{4}\b' # DD Month YYYY
        # Removed r'\b\d{4}\b' to prevent ambiguous year-only parsing
    ]

    found_date_strings = set()

    # Extract all potential date strings using regex
    for pattern in date_patterns:
        for match in re.findall(pattern, clean_query):
            found_date_strings.add(match)

    print(f"Found date strings: {found_date_strings}") # Debug print

    # Attempt to parse identified date strings into datetime objects
    for date_str in found_date_strings:
        try:
            # Removed fuzzy=True for more precise date parsing
            parsed_date = parse(date_str)
            identified_dates.append(parsed_date)
            print(f"Parsed '{date_str}' to {parsed_date}") # Debug print
        except ValueError:
            # Handle cases where `dateutil.parser.parse` fails (e.g., non-sensical dates)
            print(f"Could not parse '{date_str}'") # Debug print
            pass

    # Also check for relative dates if relevant (e.g., 'today', 'yesterday', 'tomorrow', 'last year', etc.)
    # This part is more complex and might be added later if needed.

    # Sort the dates to ensure consistency if multiple dates are found
    identified_dates.sort()

    return identified_dates

print("identify_dates function defined.")

identify_dates function defined.

## Test Identify Dates Function

### Subtask:
Test the `identify_dates` function with sample queries containing different date formats or keywords (e.g., 'yesterday', 'last year', '2014').

**Reasoning**:
Calling the `identify_dates` function with a query containing a single, explicit date in 'YYYY-MM-DD' format as per the first instruction.

In [ ]:
query_date_explicit = "What happened on 2014-07-13?"
identified_dates_explicit = identify_dates(query_date_explicit)
print(f"Query: '{query_date_explicit}'\nIdentified Dates: {identified_dates_explicit}\n")

Query: 'What happened on 2014-07-13?'
Identified Dates: [datetime.datetime(2014, 7, 13, 0, 0), datetime.datetime(2014, 7, 20, 0, 0)]

**Reasoning**:
Re-testing the `identify_dates` function with the same query after removing `fuzzy=True` to confirm accurate date extraction.

In [ ]:
query_date_explicit = "What happened on 2014-07-13?"
identified_dates_explicit = identify_dates(query_date_explicit)
print(f"Query: '{query_date_explicit}'\nIdentified Dates: {identified_dates_explicit}\n")

Query: 'What happened on 2014-07-13?'
Identified Dates: [datetime.datetime(2014, 7, 13, 0, 0), datetime.datetime(2014, 7, 20, 0, 0)]

**Reasoning**:
Calling the `identify_dates` function with the same query after adding debug prints to understand the parsing behavior.

In [ ]:
query_date_explicit = "What happened on 2014-07-13?"
identified_dates_explicit = identify_dates(query_date_explicit)
print(f"Query: '{query_date_explicit}'\nIdentified Dates: {identified_dates_explicit}\n")

Found date strings: {'2014', '2014-07-13'}
Parsed '2014' to 2014-07-20 00:00:00
Parsed '2014-07-13' to 2014-07-13 00:00:00
Query: 'What happened on 2014-07-13?'
Identified Dates: [datetime.datetime(2014, 7, 13, 0, 0), datetime.datetime(2014, 7, 20, 0, 0)]

**Reasoning**:
Calling the `identify_dates` function with the same query after removing the year-only regex pattern, to confirm that only the explicit date '2014-07-13' is identified.

In [ ]:
query_date_explicit = "What happened on 2014-07-13?"
identified_dates_explicit = identify_dates(query_date_explicit)
print(f"Query: '{query_date_explicit}'\nIdentified Dates: {identified_dates_explicit}\n")

Found date strings: {'2014-07-13'}
Parsed '2014-07-13' to 2014-07-13 00:00:00
Query: 'What happened on 2014-07-13?'
Identified Dates: [datetime.datetime(2014, 7, 13, 0, 0)]

**Reasoning**:
Calling the `identify_dates` function with a query containing a date in 'Month DD, YYYY' format to test its ability to parse different date representations.

In [ ]:
query_date_month_day_year = "Show me results from July 4, 2010."
identified_dates_mmyy = identify_dates(query_date_month_day_year)
print(f"Query: '{query_date_month_day_year}'\nIdentified Dates: {identified_dates_mmyy}\n")

Found date strings: set()
Query: 'Show me results from July 4, 2010.'
Identified Dates: []

**Reasoning**:
Calling the `identify_dates` function with the query containing 'Month DD, YYYY' format after modifying the function to handle commas, to verify correct date identification.

In [ ]:
query_date_month_day_year = "Show me results from July 4, 2010."
identified_dates_mmyy = identify_dates(query_date_month_day_year)
print(f"Query: '{query_date_month_day_year}'\nIdentified Dates: {identified_dates_mmyy}\n")

Found date strings: {'july 4, 2010'}
Parsed 'july 4, 2010' to 2010-07-04 00:00:00
Query: 'Show me results from July 4, 2010.'
Identified Dates: [datetime.datetime(2010, 7, 4, 0, 0)]

**Reasoning**:
Calling the `identify_dates` function with a query containing only a year, to test its ability to identify and parse year-only queries.

In [ ]:
query_year_only = "What were the results in 2018?"
identified_dates_year = identify_dates(query_year_only)
print(f"Query: '{query_year_only}'\nIdentified Dates: {identified_dates_year}\n")

Found date strings: set()
Query: 'What were the results in 2018?'
Identified Dates: []

**Reasoning**:
Calling the `identify_dates` function with a query containing a date in 'MM-DD-YYYY' format to test its ability to parse this common date representation.

In [ ]:
query_date_mm_dd_yyyy = "What were the results on 10-26-2005?"
identified_dates_mm_dd_yyyy = identify_dates(query_date_mm_dd_yyyy)
print(f"Query: '{query_date_mm_dd_yyyy}'\nIdentified Dates: {identified_dates_mm_dd_yyyy}\n")

Found date strings: {'10-26-2005'}
Parsed '10-26-2005' to 2005-10-26 00:00:00
Query: 'What were the results on 10-26-2005?'
Identified Dates: [datetime.datetime(2005, 10, 26, 0, 0)]

## Define Identify Tournaments Function

### Subtask:
Develop a function to identify tournament names within the query by comparing query tokens against the unique tournament names in the `results` DataFrame.

**Reasoning**:
Extract all unique tournament names from the 'tournament' column of the `results` DataFrame and store them in a set named `all_tournaments` for efficient lookup. Print the number of unique tournaments found.

In [ ]:
all_tournaments = set(results['tournament'])
print(f"Number of unique tournaments: {len(all_tournaments)}")

Number of unique tournaments: 200

**Reasoning**:
Defining the `identify_tournaments` function to preprocess the query and then iterate through the `all_tournaments` set to find tournament names present as substrings in the lowercased query.

In [ ]:
def identify_tournaments(query):
    identified_tournaments = set()
    query_lower = query.lower()

    for tournament_name in all_tournaments:
        if tournament_name.lower() in query_lower:
            identified_tournaments.add(tournament_name)

    return list(identified_tournaments)

print("identify_tournaments function defined.")

identify_tournaments function defined.

## Test Identify Tournaments Function

### Subtask:
Test the `identify_tournaments` function with sample queries containing different tournament names (e.g., 'FIFA World Cup', 'Friendly').

**Reasoning**:
Calling the `identify_tournaments` function with a query containing a common tournament name ('FIFA World Cup') as per the first instruction to test its functionality.

In [ ]:
query_fifa_world_cup = "Who won the FIFA World Cup in 2014?"
identified_tournaments_fifa = identify_tournaments(query_fifa_world_cup)
print(f"Query: '{query_fifa_world_cup}'\nIdentified Tournaments: {identified_tournaments_fifa}\n")

Query: 'Who won the FIFA World Cup in 2014?'
Identified Tournaments: ['FIFA World Cup']

**Reasoning**:
Calling the `identify_tournaments` function with a query containing a different tournament name ('Friendly') as per the subtask instructions.

In [ ]:
query_friendly = "What was the score of the friendly match yesterday?"
identified_tournaments_friendly = identify_tournaments(query_friendly)
print(f"Query: '{query_friendly}'\nIdentified Tournaments: {identified_tournaments_friendly}\n")

Query: 'What was the score of the friendly match yesterday?'
Identified Tournaments: ['Friendly']

## Define Question Type Classifier

### Subtask:
Implement a mechanism (e.g., keyword-based rules or a simple classifier) to determine the type of question being asked (e.g., 'Who won', 'What was the score', 'Which team won a tournament').

**Reasoning**:
To begin defining the question type classifier, I will set up the initial structure of the `classify_question_type` function and outline the keywords that will help determine the question's intent. This step will focus on identifying the most common question types based on explicit keywords.

In [ ]:
def classify_question_type(query):
    query_lower = query.lower()

    if any(keyword in query_lower for keyword in ['won', 'winner', 'who won', 'champion']):
        # Prioritize 'which team won tournament' if 'tournament' is also present
        if any(keyword in query_lower for keyword in ['tournament', 'cup', 'world cup', 'championship']):
            return 'Which team won tournament'
        return 'Who won'
    elif any(keyword in query_lower for keyword in ['score', 'result', 'what was the score', 'how much']):
        return 'What was the score'
    elif any(keyword in query_lower for keyword in ['played', 'match', 'game', 'between']):
        return 'Teams played'
    else:
        return 'General query'

print("classify_question_type function defined.")

classify_question_type function defined.

## Test Question Type Classifier

### Subtask:
Test the question type classifier with various sample questions to ensure it correctly categorizes the query intent.

**Reasoning**:
Calling the `classify_question_type` function with a sample query for a 'Who won' type question as per the first instruction.

In [ ]:
query_who_won = "Who won the match between Brazil and Argentina?"
classified_type_who_won = classify_question_type(query_who_won)
print(f"Query: '{query_who_won}'\nClassified Type: {classified_type_who_won}\n")

Query: 'Who won the match between Brazil and Argentina?'
Classified Type: Who won

**Reasoning**:
Calling the `classify_question_type` function with a sample query for a 'What was the score' type question as per the subtask instructions.

In [ ]:
query_score = "What was the score of the match between Germany and France?"
classified_type_score = classify_question_type(query_score)
print(f"Query: '{query_score}'\nClassified Type: {classified_type_score}\n")

Query: 'What was the score of the match between Germany and France?'
Classified Type: What was the score

**Reasoning**:
Calling the `classify_question_type` function with a sample query for a 'Which team won tournament' type question as per the subtask instructions.

In [ ]:
query_tournament_winner = "Which team won the FIFA World Cup in 2014?"
classified_type_tournament_winner = classify_question_type(query_tournament_winner)
print(f"Query: '{query_tournament_winner}'\nClassified Type: {classified_type_tournament_winner}\n")

Query: 'Which team won the FIFA World Cup in 2014?'
Classified Type: Which team won tournament

**Reasoning**:
Calling the `classify_question_type` function with a sample query for a 'Teams played' type question as per the subtask instructions.

In [ ]:
query_teams_played = "Which teams played in the final match?"
classified_type_teams_played = classify_question_type(query_teams_played)
print(f"Query: '{query_teams_played}'\nClassified Type: {classified_type_teams_played}\n")

Query: 'Which teams played in the final match?'
Classified Type: Teams played

## Define Data Extraction Function

### Subtask:
Create a function that takes identified entities (teams, dates, tournaments) and the question type, and extracts the relevant rows from the `results` DataFrame.

**Reasoning**:
Defining the `extract_data` function, which will take identified entities (teams, dates, tournaments) and the question type to filter the `results` DataFrame. This involves converting the 'date' column to datetime objects and implementing conditional filtering based on the provided entities.

In [ ]:
def extract_data(identified_teams, identified_dates, identified_tournaments, question_type):
    filtered_df = results.copy()

    # Ensure 'date' column is datetime type for proper comparison
    filtered_df['date'] = pd.to_datetime(filtered_df['date'])

    # Filter by teams
    if identified_teams:
        team_filter = filtered_df['home_team'].isin(identified_teams) | \
                      filtered_df['away_team'].isin(identified_teams)
        filtered_df = filtered_df[team_filter]

    # Filter by dates
    if identified_dates:
        # Convert identified_dates to date-only for comparison with DataFrame's date column
        dates_to_filter = [d.date() for d in identified_dates]
        filtered_df = filtered_df[filtered_df['date'].dt.date.isin(dates_to_filter)]

    # Filter by tournaments
    if identified_tournaments:
        tournament_filter = filtered_df['tournament'].isin(identified_tournaments)
        filtered_df = filtered_df[tournament_filter]

    return filtered_df

print("extract_data function defined.")

extract_data function defined.

## Test Data Extraction Function

### Subtask:
Test the data extraction function with several scenarios to confirm it retrieves the correct match results based on the input entities and question type.

**Reasoning**:
Calling the `extract_data` function with identified teams ('Brazil' and 'Argentina') and empty lists for dates and tournaments, as per the first instruction. Then, displaying the head of the resulting DataFrame to verify correct team filtering.

In [ ]:
identified_teams_scenario1 = ['Brazil', 'Argentina']
identified_dates_scenario1 = []
identified_tournaments_scenario1 = []

filtered_df_scenario1 = extract_data(identified_teams_scenario1, identified_dates_scenario1, identified_tournaments_scenario1, 'Who won')

print("Scenario 1: Matches involving Brazil or Argentina:")
print(f"Shape of filtered DataFrame: {filtered_df_scenario1.shape}")
display(filtered_df_scenario1.head())

Scenario 1: Matches involving Brazil or Argentina:
Shape of filtered DataFrame: (2024, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
145,1902-07-20,Uruguay,Argentina,0.0,6.0,Friendly,Montevideo,Uruguay,False
155,1903-09-13,Argentina,Uruguay,2.0,3.0,Friendly,Buenos Aires,Argentina,False
180,1905-08-15,Argentina,Uruguay,0.0,0.0,Copa Lipton,Buenos Aires,Argentina,False
193,1906-07-09,Argentina,South Africa,0.0,1.0,Friendly,Buenos Aires,Argentina,False
194,1906-08-15,Uruguay,Argentina,0.0,2.0,Copa Lipton,Montevideo,Uruguay,False

**Reasoning**:
Calling the `extract_data` function with identified teams ('Germany', 'France') and a specific date ('2014-07-13'), leaving the tournaments list empty. This tests the function's ability to filter by both teams and a single date. Then, displaying the head of the resulting DataFrame to verify correct filtering.

In [ ]:
identified_teams_scenario2 = ['Germany', 'France']
identified_dates_scenario2 = [datetime.datetime(2014, 7, 13, 0, 0)]
identified_tournaments_scenario2 = []

filtered_df_scenario2 = extract_data(identified_teams_scenario2, identified_dates_scenario2, identified_tournaments_scenario2, 'What was the score')

print("Scenario 2: Matches involving Germany or France on 2014-07-13:")
print(f"Shape of filtered DataFrame: {filtered_df_scenario2.shape}")
display(filtered_df_scenario2.head())

Scenario 2: Matches involving Germany or France on 2014-07-13:
Shape of filtered DataFrame: (1, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
37933,2014-07-13,Germany,Argentina,1.0,0.0,FIFA World Cup,Rio de Janeiro,Brazil,True

**Reasoning**:
Calling the `extract_data` function with a specific tournament ('FIFA World Cup') and a team ('Brazil'), leaving the dates list empty. This tests the function's ability to filter by both a tournament and a specific team. Then, displaying the head of the resulting DataFrame to verify correct filtering.

In [ ]:
identified_teams_scenario3 = ['Brazil']
identified_dates_scenario3 = []
identified_tournaments_scenario3 = ['FIFA World Cup']

filtered_df_scenario3 = extract_data(identified_teams_scenario3, identified_dates_scenario3, identified_tournaments_scenario3, 'Who won')

print("Scenario 3: Matches involving Brazil in the FIFA World Cup:")
print(f"Shape of filtered DataFrame: {filtered_df_scenario3.shape}")
display(filtered_df_scenario3.head())

Scenario 3: Matches involving Brazil in the FIFA World Cup:
Shape of filtered DataFrame: (117, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
1492,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True
1503,1930-07-20,Bolivia,Brazil,0.0,4.0,FIFA World Cup,Montevideo,Uruguay,True
1880,1934-05-27,Brazil,Spain,1.0,3.0,FIFA World Cup,Genoa,Italy,True
2329,1938-06-05,Brazil,Poland,6.0,5.0,FIFA World Cup,Strasbourg,France,True
2339,1938-06-12,Brazil,Czechoslovakia,1.0,1.0,FIFA World Cup,Bordeaux,France,True

**Reasoning**:
Calling the `extract_data` function with a combination of identified teams, dates, and tournaments to test its ability to handle all three filtering criteria simultaneously. Then, displaying the head of the resulting DataFrame to verify correct filtering.

In [ ]:
identified_teams_scenario4 = ['Germany', 'Brazil']
identified_dates_scenario4 = [datetime.datetime(2014, 7, 8, 0, 0)] # Example date for a Germany vs Brazil match in 2014 WC
identified_tournaments_scenario4 = ['FIFA World Cup']

filtered_df_scenario4 = extract_data(identified_teams_scenario4, identified_dates_scenario4, identified_tournaments_scenario4, 'What was the score')

print("Scenario 4: Matches involving Germany or Brazil on 2014-07-08 in FIFA World Cup:")
print(f"Shape of filtered DataFrame: {filtered_df_scenario4.shape}")
display(filtered_df_scenario4.head())

Scenario 4: Matches involving Germany or Brazil on 2014-07-08 in FIFA World Cup:
Shape of filtered DataFrame: (1, 9)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
37928,2014-07-08,Brazil,Germany,1.0,7.0,FIFA World Cup,Belo Horizonte,Brazil,False

In [ ]:
def generate_answer(filtered_df, question_type):
    if filtered_df.empty:
        return "No matches found based on your query."

    answer = ""

    if question_type == 'Who won':
        if len(filtered_df) == 1:
            # Handle a single match
            match = filtered_df.iloc[0]
            home_score = match['home_score']
            away_score = match['away_score']

            if pd.isna(home_score) or pd.isna(away_score):
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} had no recorded score."
            elif home_score > away_score:
                answer = f"{match['home_team']} won against {match['away_team']} with a score of {int(home_score)}-{int(away_score)} on {match['date'].strftime('%Y-%m-%d')}."
            elif away_score > home_score:
                answer = f"{match['away_team']} won against {match['home_team']} with a score of {int(away_score)}-{int(home_score)} on {match['date'].strftime('%Y-%m-%d')}."
            else:
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} was a draw with a score of {int(home_score)}-{int(away_score)}."
        else:
            # Handle multiple matches (head-to-head or general 'who won' for a set of teams)
            team_wins = {}
            for _, match in filtered_df.iterrows():
                home_score = match['home_score']
                away_score = match['away_score']
                home_team = match['home_team']
                away_team = match['away_team']

                if pd.isna(home_score) or pd.isna(away_score):
                    continue # Skip matches with missing scores

                if home_score > away_score:
                    team_wins[home_team] = team_wins.get(home_team, 0) + 1
                elif away_score > home_score:
                    team_wins[away_team] = team_wins.get(away_team, 0) + 1

            if not team_wins:
                answer = "No clear winner could be determined for these matches (possibly all draws or no scores recorded)."
            else:
                max_wins = 0
                winning_teams = []
                for team, wins in team_wins.items():
                    if wins > max_wins:
                        max_wins = wins
                        winning_teams = [team]
                    elif wins == max_wins:
                        winning_teams.append(team)

                if len(winning_teams) == 1:
                    answer = f"Overall, {winning_teams[0]} had the most wins ({max_wins}) in the queried matches."
                else:
                    answer = f"It was a close contest, with multiple teams having {max_wins} wins: {', '.join(winning_teams)}."

    elif question_type == 'What was the score':
        scores_list = []
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            if pd.isna(home_score) or pd.isna(away_score):
                scores_list.append(f"{match['home_team']} vs {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}: Score not recorded.")
            else:
                scores_list.append(f"{match['home_team']} {int(home_score)}-{int(away_score)} {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}.")
        answer = "\n".join(scores_list)

    elif question_type == 'Which team won tournament':
        # Assuming that `filtered_df` contains matches from a single tournament or relevant matches
        # A simplistic approach: team with the most wins in the filtered data is the 'winner'
        # For more complex tournament structures, this would need a more sophisticated logic
        # (e.g., identifying final match, checking specific stages).
        team_wins = {}
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            home_team = match['home_team']
            away_team = match['away_team']

            if pd.isna(home_score) or pd.isna(away_score):
                continue # Skip matches with missing scores

            if home_score > away_score:
                team_wins[home_team] = team_wins.get(home_team, 0) + 1
            elif away_score > home_score:
                team_wins[away_team] = team_wins.get(away_team, 0) + 1

        if not team_wins:
            answer = "No clear winner could be determined for the tournament (possibly all draws or no scores recorded)."
        else:
            tournament_winner = max(team_wins, key=team_wins.get)
            answer = f"The winner of the tournament based on the available matches is {tournament_winner}."

    elif question_type == 'Teams played':
        unique_teams = set()
        for _, match in filtered_df.iterrows():
            unique_teams.add(match['home_team'])
            unique_teams.add(match['away_team'])
        answer = f"The teams that played were: {', '.join(sorted(list(unique_teams)))}."

    else:
        answer = "I cannot answer this type of question yet."

    return answer

print("generate_answer function defined.")

generate_answer function defined.

## Consolidated NLQA System Dependencies

To ensure all functions are correctly defined and available, this cell consolidates all necessary imports, data loading, global variables, and helper function definitions that the `answer_query` function relies on.

In [6]:
import pandas as pd
import nltk
import re
import datetime
from google.colab import drive

# --- NLTK Downloads ---
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)

# --- Date Parsing Library Check and Install ---
try:
    from dateutil.parser import parse
except ImportError:
    print("Installing python-dateutil...")
    !pip install python-dateutil
    from dateutil.parser import parse

# Ensure Google Drive is mounted for data access
drive.mount('/content/drive', force_remount=True)

# --- Load Data and Initialize Global Variables ---
file_path = '/content/drive/MyDrive/NLP_Tishan/results.csv'
results = pd.read_csv(file_path)

all_teams = set(results['home_team']).union(set(results['away_team']))
all_tournaments = set(results['tournament'])

# --- Function Definitions ---
def preprocess_query(query):
    query = query.lower()
    query = re.sub(r'[^a-z0-9\s]', '', query)
    tokens = nltk.word_tokenize(query)
    stop_words = set(nltk.corpus.stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

def identify_team_names(query):
    preprocessed_tokens = preprocess_query(query)
    identified_teams_refined = set()
    query_lower = query.lower()
    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)
    return list(identified_teams_refined)

def identify_dates(query):
    identified_dates = []
    query_lower = query.lower()
    clean_query = re.sub(r'[^a-z0-9\s,-]', '', query_lower)
    date_patterns = [
        r'\b\d{4}[-/]\d{2}[-/]\d{2}\b', # YYYY-MM-DD or YYYY/MM/DD
        r'\b\d{2}[-/]\d{2}[-/]\d{4}\b', # MM-DD-YYYY or MM/DD/YYYY
        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{1,2},\s+\d{4}\b', # Month DD, YYYY
        r'\b\d{1,2}\s+(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{4}\b' # DD Month YYYY
    ]
    found_date_strings = set()
    for pattern in date_patterns:
        for match in re.findall(pattern, clean_query):
            found_date_strings.add(match)
    for date_str in found_date_strings:
        try:
            parsed_date = parse(date_str)
            identified_dates.append(parsed_date)
        except ValueError:
            pass
    identified_dates.sort()
    return identified_dates

def identify_tournaments(query):
    identified_tournaments = set()
    query_lower = query.lower()
    for tournament_name in all_tournaments:
        if tournament_name.lower() in query_lower:
            identified_tournaments.add(tournament_name)
    return list(identified_tournaments)

def classify_question_type(query):
    query_lower = query.lower()
    if any(keyword in query_lower for keyword in ['won', 'winner', 'who won', 'champion']):
        if any(keyword in query_lower for keyword in ['tournament', 'cup', 'world cup', 'championship']):
            return 'Which team won tournament'
        return 'Who won'
    elif any(keyword in query_lower for keyword in ['score', 'result', 'what was the score', 'how much']):
        return 'What was the score'
    elif any(keyword in query_lower for keyword in ['played', 'match', 'game', 'between']):
        return 'Teams played'
    else:
        return 'General query'

def extract_data(identified_teams, identified_dates, identified_tournaments, question_type):
    filtered_df = results.copy()
    filtered_df['date'] = pd.to_datetime(filtered_df['date'])
    if identified_teams:
        team_filter = filtered_df['home_team'].isin(identified_teams) | \
                      filtered_df['away_team'].isin(identified_teams)
        filtered_df = filtered_df[team_filter]
    if identified_dates:
        dates_to_filter = [d.date() for d in identified_dates]
        filtered_df = filtered_df[filtered_df['date'].dt.date.isin(dates_to_filter)]
    if identified_tournaments:
        tournament_filter = filtered_df['tournament'].isin(identified_tournaments)
        filtered_df = filtered_df[tournament_filter]
    return filtered_df

def generate_answer(filtered_df, question_type):
    if filtered_df.empty:
        return "No matches found based on your query."
    answer = ""
    if question_type == 'Who won':
        if len(filtered_df) == 1:
            match = filtered_df.iloc[0]
            home_score = match['home_score']
            away_score = match['away_score']
            if pd.isna(home_score) or pd.isna(away_score):
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} had no recorded score."
            elif home_score > away_score:
                answer = f"{match['home_team']} won against {match['away_team']} with a score of {int(home_score)}-{int(away_score)} on {match['date'].strftime('%Y-%m-%d')}."
            elif away_score > home_score:
                answer = f"{match['away_team']} won against {match['home_team']} with a score of {int(away_score)}-{int(home_score)} on {match['date'].strftime('%Y-%m-%d')}."
            else:
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} was a draw with a score of {int(home_score)}-{int(away_score)}."
        else:
            team_wins = {}
            for _, match in filtered_df.iterrows():
                home_score = match['home_score']
                away_score = match['away_score']
                home_team = match['home_team']
                away_team = match['away_team']
                if pd.isna(home_score) or pd.isna(away_score):
                    continue
                if home_score > away_score:
                    team_wins[home_team] = team_wins.get(home_team, 0) + 1
                elif away_score > home_score:
                    team_wins[away_team] = team_wins.get(away_team, 0) + 1
            if not team_wins:
                answer = "No clear winner could be determined for these matches (possibly all draws or no scores recorded)."
            else:
                max_wins = 0
                winning_teams = []
                for team, wins in team_wins.items():
                    if wins > max_wins:
                        max_wins = wins
                        winning_teams = [team]
                    elif wins == max_wins:
                        winning_teams.append(team)
                if len(winning_teams) == 1:
                    answer = f"Overall, {winning_teams[0]} had the most wins ({max_wins}) in the queried matches."
                else:
                    answer = f"It was a close contest, with multiple teams having {max_wins} wins: {', '.join(winning_teams)}."
    elif question_type == 'What was the score':
        scores_list = []
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            if pd.isna(home_score) or pd.isna(away_score):
                scores_list.append(f"{match['home_team']} vs {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}: Score not recorded.")
            else:
                scores_list.append(f"{match['home_team']} {int(home_score)}-{int(away_score)} {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}.")
        answer = "\n".join(scores_list)
    elif question_type == 'Which team won tournament':
        team_wins = {}
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            home_team = match['home_team']
            away_team = match['away_team']
            if pd.isna(home_score) or pd.isna(away_score):
                continue
            if home_score > away_score:
                team_wins[home_team] = team_wins.get(home_team, 0) + 1
            elif away_score > home_score:
                team_wins[away_team] = team_wins.get(away_team, 0) + 1
        if not team_wins:
            answer = "No clear winner could be determined for the tournament (possibly all draws or no scores recorded)."
        else:
            tournament_winner = max(team_wins, key=team_wins.get)
            answer = f"The winner of the tournament based on the available matches is {tournament_winner}."
    elif question_type == 'Teams played':
        unique_teams = set()
        for _, match in filtered_df.iterrows():
            unique_teams.add(match['home_team'])
            unique_teams.add(match['away_team'])
        answer = f"The teams that played were: {', '.join(sorted(list(unique_teams)))}."
    else:
        answer = "I cannot answer this type of question yet."
    return answer

print("All NLQA helper functions and dependencies defined.")

Mounted at /content/drive
All NLQA helper functions and dependencies defined.

**Reasoning**:
Calling the `generate_answer` function with `filtered_df_scenario1` (matches involving Brazil or Argentina) and the question type 'Who won', as per the first instruction.

In [ ]:
query_who_won_scenario1 = "Who won the most matches between Brazil and Argentina?"
answer_who_won_scenario1 = generate_answer(filtered_df_scenario1, 'Who won')
print(f"Query: '{query_who_won_scenario1}'\nAnswer: {answer_who_won_scenario1}\n")

Query: 'Who won the most matches between Brazil and Argentina?'
Answer: Overall, Brazil had the most wins (672) in the queried matches.

In [ ]:
query_score_scenario2 = "What was the score of the match between Germany and France on 2014-07-13?"
answer_score_scenario2 = generate_answer(filtered_df_scenario2, 'What was the score')
print(f"Query: '{query_score_scenario2}'\nAnswer: {answer_score_scenario2}\n")

Query: 'What was the score of the match between Germany and France on 2014-07-13?'
Answer: Germany 1-0 Argentina on 2014-07-13.

In [ ]:
query_tournament_winner_scenario3 = "Which team won the FIFA World Cup (among Brazil's matches)?"
answer_tournament_winner_scenario3 = generate_answer(filtered_df_scenario3, 'Which team won tournament')
print(f"Query: '{query_tournament_winner_scenario3}'\nAnswer: {answer_tournament_winner_scenario3}\n")

Query: 'Which team won the FIFA World Cup (among Brazil's matches)?'
Answer: The winner of the tournament based on the available matches is Brazil.

In [ ]:
query_teams_played_scenario4 = "Which teams played in the match between Germany and Brazil on 2014-07-08 in the FIFA World Cup?"
answer_teams_played_scenario4 = generate_answer(filtered_df_scenario4, 'Teams played')
print(f"Query: '{query_teams_played_scenario4}'\nAnswer: {answer_teams_played_scenario4}\n")

Query: 'Which teams played in the match between Germany and Brazil on 2014-07-08 in the FIFA World Cup?'
Answer: The teams that played were: Brazil, Germany.

In [7]:
def answer_query(query):
    # 1. Preprocess the query
    # The preprocess_query function is implicitly called within other functions

    # 2. Identify entities
    teams = identify_team_names(query)
    dates = identify_dates(query)
    tournaments = identify_tournaments(query)

    # 3. Classify question type
    question_type = classify_question_type(query)

    # 4. Extract data
    filtered_data = extract_data(teams, dates, tournaments, question_type)

    # 5. Generate answer
    answer = generate_answer(filtered_data, question_type)

    return answer

print("answer_query function defined.")

answer_query function defined.

In [8]:
query_test1 = "Who won the match between Brazil and Germany on 2014-07-08?"
answer_test1 = answer_query(query_test1)
print(f"Query: '{query_test1}'\nAnswer: {answer_test1}\n")

Query: 'Who won the match between Brazil and Germany on 2014-07-08?'
Answer: Germany won against Brazil with a score of 7-1 on 2014-07-08.

In [13]:
import pandas as pd
import nltk
import re
import datetime
from google.colab import drive

# --- NLTK Downloads ---
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)

# --- Date Parsing Library Check and Install ---
try:
    from dateutil.parser import parse
except ImportError:
    print("Installing python-dateutil...")
    !pip install python-dateutil
    from dateutil.parser import parse

# Ensure Google Drive is mounted for data access
drive.mount('/content/drive', force_remount=True)

# --- Load Data and Initialize Global Variables ---
file_path = '/content/drive/MyDrive/NLP_Tishan/results.csv'
results = pd.read_csv(file_path)

all_teams = set(results['home_team']).union(set(results['away_team']))
all_tournaments = set(results['tournament'])

# --- Function Definitions ---
def preprocess_query(query):
    query = query.lower()
    query = re.sub(r'[^a-z0-9\s]', '', query)
    tokens = nltk.word_tokenize(query)
    stop_words = set(nltk.corpus.stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return filtered_tokens

def identify_team_names(query):
    preprocessed_tokens = preprocess_query(query)
    identified_teams_refined = set()
    query_lower = query.lower()
    for team_name in all_teams:
        if team_name.lower() in query_lower:
            identified_teams_refined.add(team_name)
    return list(identified_teams_refined)

def identify_dates(query):
    identified_dates = []
    query_lower = query.lower()
    clean_query = re.sub(r'[^a-z0-9\s,-]', '', query_lower)
    date_patterns = [
        r'\b\d{4}[-/]\d{2}[-/]\d{2}\b', # YYYY-MM-DD or YYYY/MM/DD
        r'\b\d{2}[-/]\d{2}[-/]\d{4}\b', # MM-DD-YYYY or MM/DD/YYYY
        r'\b(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{1,2},\s+\d{4}\b', # Month DD, YYYY
        r'\b\d{1,2}\s+(?:january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s+\d{4}\b' # DD Month YYYY
    ]
    found_date_strings = set()
    for pattern in date_patterns:
        for match in re.findall(pattern, clean_query):
            found_date_strings.add(match)
    for date_str in found_date_strings:
        try:
            parsed_date = parse(date_str)
            identified_dates.append(parsed_date)
        except ValueError:
            pass
    identified_dates.sort()
    return identified_dates

def identify_tournaments(query):
    identified_tournaments = set()
    query_lower = query.lower()
    for tournament_name in all_tournaments:
        if tournament_name.lower() in query_lower:
            identified_tournaments.add(tournament_name)
    return list(identified_tournaments)

def classify_question_type(query):
    query_lower = query.lower()
    if any(keyword in query_lower for keyword in ['won', 'winner', 'who won', 'champion']):
        if any(keyword in query_lower for keyword in ['tournament', 'cup', 'world cup', 'championship']):
            return 'Which team won tournament'
        return 'Who won'
    elif any(keyword in query_lower for keyword in ['score', 'result', 'what was the score', 'how much']):
        return 'What was the score'
    elif any(keyword in query_lower for keyword in ['played', 'match', 'game', 'between']):
        return 'Teams played'
    else:
        return 'General query'

def extract_data(identified_teams, identified_dates, identified_tournaments, question_type):
    filtered_df = results.copy()
    filtered_df['date'] = pd.to_datetime(filtered_df['date'])
    if identified_teams:
        team_filter = filtered_df['home_team'].isin(identified_teams) | \
                      filtered_df['away_team'].isin(identified_teams)
        filtered_df = filtered_df[team_filter]
    if identified_dates:
        dates_to_filter = [d.date() for d in identified_dates]
        filtered_df = filtered_df[filtered_df['date'].dt.date.isin(dates_to_filter)]
    if identified_tournaments:
        tournament_filter = filtered_df['tournament'].isin(identified_tournaments)
        filtered_df = filtered_df[tournament_filter]
    return filtered_df

def generate_answer(filtered_df, question_type):
    if filtered_df.empty:
        return "No matches found based on your query."
    answer = ""
    if question_type == 'Who won':
        if len(filtered_df) == 1:
            match = filtered_df.iloc[0]
            home_score = match['home_score']
            away_score = match['away_score']
            if pd.isna(home_score) or pd.isna(away_score):
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} had no recorded score."
            elif home_score > away_score:
                answer = f"{match['home_team']} won against {match['away_team']} with a score of {int(home_score)}-{int(away_score)} on {match['date'].strftime('%Y-%m-%d')}."
            elif away_score > home_score:
                answer = f"{match['away_team']} won against {match['home_team']} with a score of {int(away_score)}-{int(home_score)} on {match['date'].strftime('%Y-%m-%d')}."
            else:
                answer = f"The match between {match['home_team']} and {match['away_team']} on {match['date'].strftime('%Y-%m-%d')} was a draw with a score of {int(home_score)}-{int(away_score)}."
        else:
            team_wins = {}
            for _, match in filtered_df.iterrows():
                home_score = match['home_score']
                away_score = match['away_score']
                home_team = match['home_team']
                away_team = match['away_team']
                if pd.isna(home_score) or pd.isna(away_score):
                    continue
                if home_score > away_score:
                    team_wins[home_team] = team_wins.get(home_team, 0) + 1
                elif away_score > home_score:
                    team_wins[away_team] = team_wins.get(away_team, 0) + 1
            if not team_wins:
                answer = "No clear winner could be determined for these matches (possibly all draws or no scores recorded). Please refine your query."
            else:
                max_wins = 0
                winning_teams = []
                for team, wins in team_wins.items():
                    if wins > max_wins:
                        max_wins = wins
                        winning_teams = [team]
                    elif wins == max_wins:
                        winning_teams.append(team)
                if len(winning_teams) == 1:
                    answer = f"Overall, {winning_teams[0]} had the most wins ({max_wins}) in the queried matches."
                else:
                    answer = f"It was a close contest, with multiple teams having {max_wins} wins: {', '.join(winning_teams)}."
    elif question_type == 'What was the score':
        scores_list = []
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            if pd.isna(home_score) or pd.isna(away_score):
                scores_list.append(f"{match['home_team']} vs {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}: Score not recorded.")
            else:
                scores_list.append(f"{match['home_team']} {int(home_score)}-{int(away_score)} {match['away_team']} on {match['date'].strftime('%Y-%m-%d')}.")
        answer = "\n".join(scores_list)
    elif question_type == 'Which team won tournament':
        team_wins = {}
        for _, match in filtered_df.iterrows():
            home_score = match['home_score']
            away_score = match['away_score']
            home_team = match['home_team']
            away_team = match['away_team']
            if pd.isna(home_score) or pd.isna(away_score):
                continue
            if home_score > away_score:
                team_wins[home_team] = team_wins.get(home_team, 0) + 1
            elif away_score > home_score:
                team_wins[away_team] = team_wins.get(away_team, 0) + 1
        if not team_wins:
            answer = "No clear winner could be determined for the tournament (possibly all draws or no scores recorded)."
        else:
            tournament_winner = max(team_wins, key=team_wins.get)
            answer = f"The winner of the tournament based on the available matches is {tournament_winner}."
    elif question_type == 'Teams played':
        unique_teams = set()
        for _, match in filtered_df.iterrows():
            unique_teams.add(match['home_team'])
            unique_teams.add(match['away_team'])
        answer = f"The teams that played were: {', '.join(sorted(list(unique_teams)))}."
    else:
        answer = "I cannot answer this type of question yet."
    return answer

def answer_query(query):
    # 1. Preprocess the query
    # The preprocess_query function is implicitly called within other functions

    # 2. Identify entities
    teams = identify_team_names(query)
    dates = identify_dates(query)
    tournaments = identify_tournaments(query)

    # 3. Classify question type
    question_type = classify_question_type(query)

    # 4. Extract data
    filtered_data = extract_data(teams, dates, tournaments, question_type)

    # 5. Generate answer
    answer = generate_answer(filtered_data, question_type)

    return answer

query_test1 = "Who won the match between Brazil and Germany on 2014-07-08?"
answer_test1 = answer_query(query_test1)
print(f"Query: '{query_test1}'\nAnswer: {answer_test1}\n")

Mounted at /content/drive
Query: 'Who won the match between Brazil and Germany on 2014-07-08?'
Answer: Germany won against Brazil with a score of 7-1 on 2014-07-08.